# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "thunderbolt" "nvme" "usbhid" "usb_storage" "sd_mod" "rtsx_pci_sdmmc" ];
  boot.initrd.kernelModules = [ "nvidia" "nvidia_modeset" "nvidia_uvm" "nvidia_drm" ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/763776eb-9cfd-4b03-a676-859e0000126c";
      fsType = "btrfs";
      options = [ "noatime" "compress-force=zstd:1" "commit=120" "space_cache=v2" "ssd" "discard=async" "autodefrag" "subvol=@" ];
    };

  fileSystems."/home" =
    { device = "/dev/disk/by-uuid/763776eb-9cfd-4b03-a676-859e0000126c";
      fsType = "btrfs";
      options = [ "nodev" "noatime" "compress-force=zstd:1" "commit=120" "space_cache=v2" "ssd" "discard=async" "autodefrag" "subvol=@home" ];
    };

  fileSystems."/var" =
    { device = "/dev/disk/by-uuid/763776eb-9cfd-4b03-a676-859e0000126c";
      fsType = "btrfs";
      options = [ "nodev" "nosuid" "noexec" "noatime" "compress-force=zstd:1" "commit=120" "space_cache=v2" "ssd" "discard=async" "autodefrag" "subvol=@var" ];
    };

  fileSystems."/nix" =
    { device = "/dev/disk/by-uuid/763776eb-9cfd-4b03-a676-859e0000126c";
      fsType = "btrfs";
      options = [ "noatime" "compress-force=zstd:1" "commit=120" "space_cache=v2" "ssd" "discard=async" "autodefrag" "subvol=@nix" ];
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/6980-C93A";
      fsType = "vfat";
      options = [ "fmask=0022" "dmask=0022" ];
    };

  swapDevices = [ ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp47s0.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlp45s0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
